name: Create Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit message
        id: get_message
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Get version from pom.xml
        id: get_version
        run: |
          VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec -f pom.xml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Find JAR Path
        id: find_jar
        run: |
          JAR_PATH=$(find target/ -type f -name "*.jar" -printf "%p" | head -n 1)
          echo "jar_path=$JAR_PATH" >> $GITHUB_OUTPUT
          echo "jar_name=$(basename $JAR_PATH)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body: ${{ steps.get_message.outputs.message }}
          draft: false
          prerelease: false
          files: ${{ steps.find_jar.outputs.jar_path }}